---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tabby-operator
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.spaceship.com
  resources:
  - networkattachments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.spaceship.com
  resources:
  - networkattachments/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.spaceship.com
  resources:
  - networkattachments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud.spaceship.com
  resources:
  - networks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.spaceship.com
  resources:
  - networks/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.spaceship.com
  resources:
  - networks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances
  verbs:
  - get
  - list
  - watch
