apiVersion: cloud.spaceship.com/v1alpha1
kind: Network
metadata:
  labels:
    app.kubernetes.io/name: network
    app.kubernetes.io/instance: network-sample
    app.kubernetes.io/part-of: tabby-cni-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: tabby-cni-controller
  name: br2705
spec:
  nodeSelectors:
  - matchLabels:
      beta.kubernetes.io/arch: amd64
  bridge:
    - name: br2705
      mtu: 9000
      ports:
        - name: bond1
          vlan: 2705
          mtu: 9000
