name: Build Docker Images

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    env:
      HARBOR_ROBOT_PASSWORD: ${{ secrets.HARBOR_TOKEN_ROBOT_INFRASTRUCTURE }}
      HARBOR_ROBOT_USERNAME: "robot$infrastructure+infrastructure"
      HARBOR_ENDPOINT: "harbor-bedrock.namecheapcloud.net"
      GO_VERSION: "1.19"
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set image tag
        id: image-tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Set Harbor image name
        id: harbor-image-name
        run: |
          NAME=${HARBOR_ENDPOINT}/infrastructure/tabby-operator
          echo "name=$NAME" >> $GITHUB_OUTPUT

      - name: Log into Harbor
        run: docker login -u ${HARBOR_ROBOT_USERNAME} -p ${HARBOR_ROBOT_PASSWORD} ${HARBOR_ENDPOINT}

      - name: Pull latest image to use for cache
        run: docker pull ${{ steps.harbor-image-name.outputs.name }}:latest || true

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build the Docker image
        run: |
          make docker-build IMG=${{ steps.harbor-image-name.outputs.name }}:${{ steps.image-tag.outputs.tag }}
          docker tag ${{ steps.harbor-image-name.outputs.name }}:${{ steps.image-tag.outputs.tag }} \
            ${{ steps.harbor-image-name.outputs.name }}:latest

      - name: Upload Docker image with the version tag to Harbor
        run: |
          HARBOR_IMAGE=${{ steps.harbor-image-name.outputs.name }}:${{ steps.image-tag.outputs.tag }}
          docker push $HARBOR_IMAGE

      - name: Upload Docker image as latest to Harbor
        run: docker push ${{ steps.harbor-image-name.outputs.name }}:latest
